import newAccordion from './includes/newAccordion.js';
import fixHeight from './includes/fixHeight.js';
import modal from './includes/modal.js';
import sidebar from './includes/sidebar.js';
import content from './includes/content.js';
import select from './includes/select.js';
import phoneMask from './includes/phoneMask.js';
import isDropdown from './includes/isDropdown.js';
import loadMore from './includes/loadMore.js';
import closeAlert from './includes/closeAlert.js';
import profileFormValidation from './includes/profileFormValidation.js';
import searchFormValidation from './includes/searchFormValidation.js';
import passwordFormValidation from './includes/passwordFormValidation.js';
import bookmarkFormValidation from './includes/bookmarkFormValidation.js';
import fileFormValidation from './includes/fileFormValidation.js';
import createFormValidation from './includes/createFormValidation.js';
import modalSearchFormValidation from './includes/modalSearchFormValidation.js';
import filter from './includes/filter.js';
import initTabs from './includes/initTabs.js';
import tariffsSlider from './includes/tariffsSlider.js';
import tips from './includes/tips.js';
import headerToggle from './includes/headerToggle.js';
import filterToggle from './includes/filterToggle.js';
import recommendedCheckbox from './includes/recommendedCheckbox.js';
import scrollToId from './includes/scrollToId.js';
import codex from './includes/codex.js';
import tooltips from './includes/tooltips.js';
import airDatepicker from './includes/airDatepicker.js';
import '../sass/main.sass';


newAccordion();
fixHeight();
modal();
sidebar();
content();
select();
phoneMask();
isDropdown();
loadMore();
closeAlert();
profileFormValidation();
searchFormValidation();
passwordFormValidation();
bookmarkFormValidation();
fileFormValidation();
createFormValidation();
modalSearchFormValidation();
filter();
initTabs();
tariffsSlider();
codex();
// tips();
headerToggle();
filterToggle();
recommendedCheckbox();
scrollToId();
tooltips();
airDatepicker();
